#Configuation for robot odometry EKF
#
frequency: 50

odom0: /jackal_velocity_controller/odom
odom0_config: [false, false, false,
               true, true, true,
               true, true, true,
               false, false, false,
               false, false, false]
odom0_differential: true

imu0: /imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, true, false]
imu0_differential: true

odom_frame: odom
base_link_frame: base_link
world_frame: odom

predict_to_current_time: true